### ISSUE TITLE
Upload apk results in: Invalid array length

### ISSUE THREAD

**Issue by vanlooverenkoen** [serverpod/serverpod#3633]
### Describe the bug

For some reason are my apk uploads resulting in an `Invalid array length`

https://github.com/serverpod/serverpod/blob/main/packages/serverpod_client/lib/src/file_uploader.dart#L48

```
      try {
        var result = await http.post(
          _uploadDescription.url,
          body: await _readStreamData(stream),
          headers: {
            'Content-Type': 'application/octet-stream',
            'Accept': '*/*',
          },
        );
        return result.statusCode == 200;
      } catch (e) {
        return false; // I end up here with an `Invalid array length`  error
      }
```

### To reproduce

This is what i
```
var uploader = FileUploader(uploadDescription);
final result = await uploader.uploadByteData(ByteData.view(fileBytes.buffer));
```

Or this
```
var uploader = FileUploader(uploadDescription);
final fileStream = Stream.value(fileBytes.toList());
final length = fileBytes.length;
final result = await uploader.upload(fileStream, length);
```

Both of them result false.

### Expected behavior

I expect the upload to succeed

### Library version

2.8.0

### Platform information

Web

### How experienced are you with this library?

Expert - Experienced and comfortable with using this library in complex projects

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by SandPod** [comment]
Thanks for the report!

We will try to get to this as soon as possible 👍

**Comment by vanlooverenkoen** [comment]
@SandPod any idea why this is failing? I think my setup is correct (because it works for ipa files, they are smaller so maybe that is the issue?)

I also have set 
`maxRequestSize: 200000000`

**Comment by SandPod** [comment]
Sorry, I have not been able to dig into this one yet.

I have added it to our list over prioritized bugs. I hope that we can give you a response on this soon.

**Comment by nielsenko** [comment]
@vanlooverenkoen How big is the apk you are trying to upload? What is the `uploadDescription` passed? (or just the url). I see we don't trace anything about the error, but did you try to set a breakpoint in the catch clause to see the actual exception? I would like to know the exact type, and any related data it might carry.

**Comment by nielsenko** [comment]
What runtime are you using?

**Comment by vanlooverenkoen** [comment]
The uploadDescription is done exactly how it was documented:
https://docs.serverpod.dev/concepts/file-uploads#client-side-code

The apk is 71mb 

The error that I found was `Invalid array length`, I'm not sure where I can get extra info on this error

**Comment by vanlooverenkoen** [comment]
What do you mean with runtime? 

develop
monolith

**Comment by vanlooverenkoen** [comment]
Let me try and get the runtimeType of that specific error.

**Comment by vanlooverenkoen** [comment]
I am also running on web. Maybe that is related? Using https://pub.dev/packages/file_picker

**Comment by vanlooverenkoen** [comment]
`JSRangeError` is the actual error.

**Comment by vanlooverenkoen** [comment]
Unfortunately this is the stacktrace:

```
ERROR: Invalid argument: Invalid array length
runtimeType: JSRangeError
Exception: Failed to upload file
dart:sdk_internal 3747:11                                                                             throw_
package:impaktfull_dashboard/repo/app/apps/app_testing/app_testing_app_repository.dart.lib.js 175:49  <fn>
dart:sdk_internal 44282:13                                                                            <fn>
dart:sdk_internal 44292:7                                                                             <fn>
dart:sdk_internal 44259:42                                                                            <fn>
dart:sdk_internal 44812:46                                                                            _rootRunUnary
dart:sdk_internal 3792:46                                                                             tear
dart:sdk_internal 42710:14                                                                            runUnary
dart:sdk_internal 35859:26                                                                            handleValue
dart:sdk_internal 36558:47                                                                            handleValueCallback
dart:sdk_internal 36596:15                                                                            _propagateToListeners
dart:sdk_internal 36415:21                                                                            [_completeWithValue]
dart:sdk_internal 43617:42                                                                            complete
dart:sdk_internal 44250:15                                                                            _asyncReturn
package:serverpod_client/src/file_uploader.dart.lib.js 252:28                                         <fn>
dart:sdk_internal 44282:13                                                                            <fn>
dart:sdk_internal 44292:7                                                                             <fn>
dart:sdk_internal 44262:7                                                                             <fn>
dart:sdk_internal 44825:46                                                                            _rootRunBinary
dart:sdk_internal 3792:46                                                                             tear
dart:sdk_internal 42716:14                                                                            runBinary
dart:sdk_internal 35870:30                                                                            handleError
dart:sdk_internal 36574:49                                                                            handleError
dart:sdk_internal 36600:15                                                                            _propagateToListeners
dart:sdk_internal 36430:21                                                                            [_completeErrorObject]
dart:sdk_internal 36433:33                                                                            [_completeError]
dart:sdk_internal 43623:38                                                                            completeError
dart:sdk_internal 44254:15                                                                            _asyncRethrow
package:serverpod_client/src/file_uploader.dart.lib.js 320:28                                         <fn>
dart:sdk_internal 44282:13                                                                            <fn>
dart:sdk_internal 44292:7                                                                             <fn>
dart:sdk_internal 44259:42                                                                            <fn>
dart:sdk_internal 44812:46                                                                            _rootRunUnary
dart:sdk_internal 3792:46                                                                             tear
dart:sdk_internal 42710:14                                                                            runUnary
dart:sdk_internal 35859:26                                                                            handleValue
dart:sdk_internal 36558:47                                                                            handleValueCallback
dart:sdk_internal 36596:15                                                                            _propagateToListeners
dart:sdk_internal 36415:21                                                                            [_completeWithValue]
dart:sdk_internal 36461:33                                                                            callback
dart:sdk_internal 44642:13                                                                            _microtaskLoop
dart:sdk_internal 44649:13                                                                            _startMicrotaskLoop
dart:sdk_internal 3792:46                                                                             tear
dart:sdk_internal 36899:9                                                                             <fn>
```

**Comment by nielsenko** [comment]
Yes I was suspecting you used JS, hence the question about runtime. I believe the `Invalid array length` error message is actually from the JS runtime.

The current code in `file_uploader.dart` is dumb in that it reads the entire file into memory (see `_readStreamData`) before actually sending it over the wire. We should fix that.

71MB as a byte array is way below 2^32-1 (the maximum length of a JS array according to the ECMA standard), but you get this same error if you run out of memory.

The problem is:

- 71MB file = ~71 million bytes
- `List<int>` in Dart/Flutter web has significant memory overhead per element
- Each `int` in a `List<int>` uses much more than 1 byte (typically 8+ bytes due to boxing)
- Total memory usage could be 500MB-1GB+ for that list 😳

**Comment by vanlooverenkoen** [comment]
Makes sense why the 13mb ipa file does work!

Also makes sense why the UI freezes when starting the upload.
I thought I had logged this before but I can not find it. anywhere.

Here is the video of the upload again.
https://github.com/user-attachments/assets/2996e0b1-bd7c-42c9-86bf-519314544d81

**Comment by vanlooverenkoen** [comment]
Thanks @nielsenko for your fast intervention!! Once again great Serverpod work!!

**Comment by nielsenko** [comment]
@vanlooverenkoen The fix avoids the generic `List<int>` and instead uses a `Uint8List` byte buffer internally. You can try it out by updating your `serverpod_client` dependency to:
```yaml
dependencies:
  serverpod_client:
    git:
      url: https://github.com/nielsenko/serverpod.git
      ref: fix-3633-stream-reading
      path: packages/serverpod_client
```
You may want to subscribe to #3692, as this can be improved further.

**Comment by vanlooverenkoen** [comment]
Hmm still the same issue 

`Invalid argument: Invalid array length`

`JSRangeError`

Also the UI still hangs.

**Comment by nielsenko** [comment]
Could you check your `pubspec.lock`? This should give about a factor of 8 in memory, due to the internal `Uint8List` buffer, which should bring `71MB` below the memory use of the `13MB` apk you successfully uploaded before.

**Comment by vanlooverenkoen** [comment]
This is inside my lock file:

```
  serverpod_client:
    dependency: transitive
    description:
      name: serverpod_client
      sha256: "5865a1430f3eba167fa37fbd543e6975f26592da32ad8d7c5e23e4c15dbf8c4c"
      url: "https://pub.dev"
    source: hosted
    version: "2.8.0"
```

I also debugged and saw the new code was being used as well

**Comment by nielsenko** [comment]
@vanlooverenkoen This is not what I would expect. It should look like:
```yaml
  serverpod_client:
    dependency: "direct main"
    description:
      path: "packages/serverpod_client"
      ref: fix-3633-stream-reading
      resolved-ref: "66e401edcd272bef5b30f706d3be60bcce04d023"
      url: "https://github.com/nielsenko/serverpod.git"
    source: git
    version: "2.8.0"
```
Did you take a direct dependency on "my" serverpod_client? Did you run `dart pub upgrade`?

**Comment by vanlooverenkoen** [comment]
Oh sorry the snippet was from the server pubspec.lock

This is the frontend
![Image](https://github.com/user-attachments/assets/6f195301-79eb-43e2-9e98-1a066a878b9a)

This is my pubspec
```
dependency_overrides:
  serverpod_client:
    git:
      url: https://github.com/nielsenko/serverpod.git
      ref: fix-3633-stream-reading
      path: packages/serverpod_client
```

**Comment by vanlooverenkoen** [comment]
I removed the pubspec.lock and I just get the same result. 
When running the app I still get the 

```
Invalid argument: Invalid array length
```

```
JSRangeError
```

**Comment by vanlooverenkoen** [comment]
@nielsenko wouldn't it make more sense to use a `StreamedRequest` instead? And upload the requests in chunks?

**Comment by vanlooverenkoen** [comment]
I just fixed the issue here locally. Let me create a new Pull Request

**Comment by vanlooverenkoen** [comment]
@nielsenko https://github.com/serverpod/serverpod/pull/3697

**Comment by vanlooverenkoen** [comment]
I did not see you already created this one: https://github.com/serverpod/serverpod/pull/3695

The `StreamedRequest` does work indeed (at least the PR I created is what worked perfectly)

**Comment by nielsenko** [comment]
You can try my PR with:
```dart
  serverpod_client:
    git:
      url: https://github.com/nielsenko/serverpod.git
      ref: uploader-streaming
      path: packages/serverpod_client
```
It should land soon.

**Comment by nielsenko** [comment]
@vanlooverenkoen I wasn't aware you intended to work on this.

**Comment by vanlooverenkoen** [comment]
No worries, I was just playing around in debugging and accidentally found the fix :D

**Comment by vanlooverenkoen** [comment]
Yes this works! Also the UI thread is not frozen anymore! Good job @nielsenko
